Traceback (most recent call last):
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from azure.core.credentials import AzureKeyCredential
from azure.search.documents.indexes.models import (
    SearchIndexerDataContainer,
    SearchIndexerDataSourceConnection,
    SearchIndex,
    SearchIndexer,
    SimpleField,
    SearchFieldDataType,
)
from azure.search.documents.indexes import SearchIndexClient, SearchIndexerClient

service_endpoint = os.environ["service_endpoint"]


def create_indexer(indexer_name, data_source_name, storage_account_connection_string, target_index_name):
    indexer_client = SearchIndexerClient(service_endpoint, AzureKeyCredential(key))

    # Create a datasource
    container = SearchIndexerDataContainer(name="docs")

    # ONLY ONE TIME YOU HAVE TO CREATE THE CONNECTION
    # data_source_connection = SearchIndexerDataSourceConnection(
    #     name=data_source_name, type="azureblob", 
    #     connection_string=storage_account_connection_string, 
    #     container=container
    # )
    # data_source = indexer_client.create_data_source_connection(data_source_connection)

    # Create the indexer
    indexer = SearchIndexer(
        name=indexer_name, data_source_name=data_source_name, target_index_name=target_index_name
    )
    result = indexer_client.create_indexer(indexer)
    print(f"Created a new Indexer {indexer_name}")

create_indexer(indexer_name="myindexer", data_source_name="docs", storage_account_connection_string=storage_account_connection_string, target_index_name=search_index_name)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mHttpResponseError[0m                         Traceback (most recent call last)
Cell [1;32mIn[8], line 36[0m
[0;32m     33[0m     result [38;5;241m=[39m indexer_client[38;5;241m.[39mcreate_indexer(indexer)
[0;32m     34[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mCreated a new Indexer [39m[38;5;132;01m{[39;00mindexer_name[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m---> 36[0m [43mcreate_indexer[49m[43m([49m[43mindexer_name[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mmyindexer[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mdata_source_name[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mdocs[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mstorage_account_connection_string[49m[38;5;241;43m=[39;49m[43mstorage_account_connection_string[49m[43m,[49m[43m [49m[43mtarget_index_name[49m[38;5;241;43m=[39;49m[43msearch_index_name[49m[43m)[49m

Cell [1;32mIn[8], line 33[0m, in [0;36mcreate_indexer[1;34m(indexer_name, data_source_name, storage_account_connection_string, target_index_name)[0m
[0;32m     21[0m [38;5;66;03m# ONLY ONE TIME YOU HAVE TO CREATE THE CONNECTION[39;00m
[0;32m     22[0m [38;5;66;03m# data_source_connection = SearchIndexerDataSourceConnection([39;00m
[0;32m     23[0m [38;5;66;03m#     name=data_source_name, type="azureblob", [39;00m
[1;32m   (...)[0m
[0;32m     28[0m 
[0;32m     29[0m [38;5;66;03m# Create the indexer[39;00m
[0;32m     30[0m indexer [38;5;241m=[39m SearchIndexer(
[0;32m     31[0m     name[38;5;241m=[39mindexer_name, data_source_name[38;5;241m=[39mdata_source_name, target_index_name[38;5;241m=[39mtarget_index_name
[0;32m     32[0m )
[1;32m---> 33[0m result [38;5;241m=[39m [43mindexer_client[49m[38;5;241;43m.[39;49m[43mcreate_indexer[49m[43m([49m[43mindexer[49m[43m)[49m
[0;32m     34[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mCreated a new Indexer [39m[38;5;132;01m{[39;00mindexer_name[38;5;132;01m}[39;00m[38;5;124m"[39m)

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\azure\core\tracing\decorator.py:78[0m, in [0;36mdistributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer[1;34m(*args, **kwargs)[0m
[0;32m     76[0m span_impl_type [38;5;241m=[39m settings[38;5;241m.[39mtracing_implementation()
[0;32m     77[0m [38;5;28;01mif[39;00m span_impl_type [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m---> 78[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m     80[0m [38;5;66;03m# Merge span is parameter is set, but only if no explicit parent are passed[39;00m
[0;32m     81[0m [38;5;28;01mif[39;00m merge_span [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m passed_in_parent:

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\azure\search\documents\indexes\_search_indexer_client.py:100[0m, in [0;36mSearchIndexerClient.create_indexer[1;34m(self, indexer, **kwargs)[0m
[0;32m     83[0m [38;5;250m[39m[38;5;124;03m"""Creates a new SearchIndexer.[39;00m
[0;32m     84[0m 
[0;32m     85[0m [38;5;124;03m:param indexer: The definition of the indexer to create.[39;00m
[1;32m   (...)[0m
[0;32m     97[0m [38;5;124;03m        :caption: Create a SearchIndexer[39;00m
[0;32m     98[0m [38;5;124;03m"""[39;00m
[0;32m     99[0m kwargs[[38;5;124m"[39m[38;5;124mheaders[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_merge_client_headers(kwargs[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mheaders[39m[38;5;124m"[39m))
[1;32m--> 100[0m result [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_client[49m[38;5;241;43m.[39;49m[43mindexers[49m[38;5;241;43m.[39;49m[43mcreate[49m[43m([49m[43mindexer[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m    101[0m [38;5;28;01mreturn[39;00m result

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\azure\core\tracing\decorator.py:78[0m, in [0;36mdistributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer[1;34m(*args, **kwargs)[0m
[0;32m     76[0m span_impl_type [38;5;241m=[39m settings[38;5;241m.[39mtracing_implementation()
[0;32m     77[0m [38;5;28;01mif[39;00m span_impl_type [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m---> 78[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m     80[0m [38;5;66;03m# Merge span is parameter is set, but only if no explicit parent are passed[39;00m
[0;32m     81[0m [38;5;28;01mif[39;00m merge_span [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m passed_in_parent:

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexers_operations.py:955[0m, in [0;36mIndexersOperations.create[1;34m(self, indexer, request_options, **kwargs)[0m
[0;32m    953[0m     map_error(status_code[38;5;241m=[39mresponse[38;5;241m.[39mstatus_code, response[38;5;241m=[39mresponse, error_map[38;5;241m=[39merror_map)
[0;32m    954[0m     error [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_deserialize[38;5;241m.[39mfailsafe_deserialize(_models[38;5;241m.[39mSearchError, pipeline_response)
[1;32m--> 955[0m     [38;5;28;01mraise[39;00m HttpResponseError(response[38;5;241m=[39mresponse, model[38;5;241m=[39merror)
[0;32m    957[0m deserialized [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_deserialize([38;5;124m"[39m[38;5;124mSearchIndexer[39m[38;5;124m"[39m, pipeline_response)
[0;32m    959[0m [38;5;28;01mif[39;00m [38;5;28mcls[39m:

[1;31mHttpResponseError[0m: () Cannot create indexer 'myindexer' because an indexer with that name already exists
Code: 
Message: Cannot create indexer 'myindexer' because an indexer with that name already exists

