Traceback (most recent call last):
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
chunks = create_chunks(markdown_documents)
------------------

----- stdout -----
Creating chunks...
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\text_splitter.py:248[0m, in [0;36mTextSplitter.from_tiktoken_encoder[1;34m(cls, encoding_name, model_name, allowed_special, disallowed_special, **kwargs)[0m
[0;32m    247[0m [38;5;28;01mtry[39;00m:
[1;32m--> 248[0m     [38;5;28;01mimport[39;00m [38;5;21;01mtiktoken[39;00m
[0;32m    249[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

[1;31mModuleNotFoundError[0m: No module named 'tiktoken'

During handling of the above exception, another exception occurred:

[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[11], line 1[0m
[1;32m----> 1[0m chunks [38;5;241m=[39m [43mcreate_chunks[49m[43m([49m[43mmarkdown_documents[49m[43m)[49m

Cell [1;32mIn[10], line 3[0m, in [0;36mcreate_chunks[1;34m(documents)[0m
[0;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mcreate_chunks[39m(documents: [38;5;28mlist[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mlist[39m:
[0;32m      2[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mCreating chunks...[39m[38;5;124m"[39m)
[1;32m----> 3[0m     markdown_splitter [38;5;241m=[39m [43mMarkdownTextSplitter[49m[38;5;241;43m.[39;49m[43mfrom_tiktoken_encoder[49m[43m([49m
[0;32m      4[0m [43m        [49m[43mchunk_size[49m[38;5;241;43m=[39;49m[38;5;241;43m300[39;49m[43m,[49m[43m [49m[43mchunk_overlap[49m[38;5;241;43m=[39;49m[38;5;241;43m30[39;49m
[0;32m      5[0m [43m    [49m[43m)[49m
[0;32m      6[0m     lengths [38;5;241m=[39m {}
[0;32m      7[0m     all_chunks [38;5;241m=[39m []

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\text_splitter.py:250[0m, in [0;36mTextSplitter.from_tiktoken_encoder[1;34m(cls, encoding_name, model_name, allowed_special, disallowed_special, **kwargs)[0m
[0;32m    248[0m     [38;5;28;01mimport[39;00m [38;5;21;01mtiktoken[39;00m
[0;32m    249[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m--> 250[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[0;32m    251[0m         [38;5;124m"[39m[38;5;124mCould not import tiktoken python package. [39m[38;5;124m"[39m
[0;32m    252[0m         [38;5;124m"[39m[38;5;124mThis is needed in order to calculate max_tokens_for_prompt. [39m[38;5;124m"[39m
[0;32m    253[0m         [38;5;124m"[39m[38;5;124mPlease install it with `pip install tiktoken`.[39m[38;5;124m"[39m
[0;32m    254[0m     )
[0;32m    256[0m [38;5;28;01mif[39;00m model_name [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m    257[0m     enc [38;5;241m=[39m tiktoken[38;5;241m.[39mencoding_for_model(model_name)

[1;31mImportError[0m: Could not import tiktoken python package. This is needed in order to calculate max_tokens_for_prompt. Please install it with `pip install tiktoken`.

