Traceback (most recent call last):
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
query = "tools for software development"

query_embeddings = get_query_embedding(query)
vector_query = VectorizedQuery(
    vector=query_embeddings[0], k_nearest_neighbors=1, fields="chunkContentVector"
)

results = search_client.search(
    search_text=None,
    vector_queries=[vector_query],
    select=["chunkId", "chunkContent", "source"],
    top=1,
)

for result in results:
    print(f"chunkId: {result['chunkId']}")
    print(f"source: {result['source']}")
    print(f"Score: {result['@search.score']}")
    print(f"chunkContent: {result['chunkContent']}")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[4], line 3[0m
[0;32m      1[0m query [38;5;241m=[39m [38;5;124m"[39m[38;5;124mtools for software development[39m[38;5;124m"[39m
[1;32m----> 3[0m query_embeddings [38;5;241m=[39m [43mget_query_embedding[49m(query)
[0;32m      4[0m vector_query [38;5;241m=[39m VectorizedQuery(
[0;32m      5[0m     vector[38;5;241m=[39mquery_embeddings[[38;5;241m0[39m], k_nearest_neighbors[38;5;241m=[39m[38;5;241m1[39m, fields[38;5;241m=[39m[38;5;124m"[39m[38;5;124mchunkContentVector[39m[38;5;124m"[39m
[0;32m      6[0m )
[0;32m      8[0m results [38;5;241m=[39m search_client[38;5;241m.[39msearch(
[0;32m      9[0m     search_text[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m     10[0m     vector_queries[38;5;241m=[39m[vector_query],
[0;32m     11[0m     select[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mchunkId[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mchunkContent[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124msource[39m[38;5;124m"[39m],
[0;32m     12[0m     top[38;5;241m=[39m[38;5;241m1[39m,
[0;32m     13[0m )

[1;31mNameError[0m: name 'get_query_embedding' is not defined

